name: Retrieve Branch Name
on:
  push:
    branches:
      - '*'

jobs:
  create-dev-clones:
    runs-on: ubuntu-latest
    steps:
      - name: 🪄 Get branch names 🪄
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: 🐛 Get current branch 🐛
        run: |
          echo "${{ steps.branch-names.outputs.current_branch }}"